export const Genre: { title: string; image: string; description: string; color: string }[] = [
  {
    title: "Alternative",
    image: "1.jpg",
    description: "This is the description of Alternative.",
    color: "red-500",
  },
  {
    title: "Blues",
    image: "2.jpg",
    description: "This is the description of Blues.",
    color: "blue-500",
  },
  {
    title: "Classical",
    image: "3.jpg",
    description: "This is the description of Classical.",
    color: "yellow-500",
  },
  {
    title: "Country",
    image: "4.jpg",
    description: "This is the description of Country.",
    color: "green-500",
  },
  {
    title: "Dance",
    image: "5.jpg",
    description: "This is the description of Dance.",
    color: "purple-500",
  },
  {
    title: "Electronic",
    image: "6.jpg",
    description: "This is the description of Electronic.",
    color: "pink-500",
  },
  {
    title: "Folk",
    image: "7.jpg",
    description: "This is the description of Folk.",
    color: "orange-500",
  },
  {
    title: "Hip Hop",
    image: "8.jpg",
    description: "This is the description of Hip Hop.",
    color: "teal-500",
  },
  {
    title: "Indie",
    image: "9.jpg",
    description: "This is the description of Indie.",
    color: "lime-500",
  },
  {
    title: "Jazz",
    image: "10.jpg",
    description: "This is the description of Jazz.",
    color: "red-300",
  },
  {
    title: "Latin",
    image: "11.jpg",
    description: "This is the description of Latin.",
    color: "blue-300",
  },
  {
    title: "Metal",
    image: "12.jpg",
    description: "This is the description of Metal.",
    color: "yellow-300",
  },
  {
    title: "Pop",
    image: "13.jpg",
    description: "This is the description of Pop.",
    color: "green-300",
  },
  {
    title: "Punk",
    image: "14.jpg",
    description: "This is the description of Punk.",
    color: "purple-300",
  },
  {
    title: "R&B",
    image: "15.jpg",
    description: "This is the description of R&B.",
    color: "pink-300",
  },
  {
    title: "Reggae",
    image: "16.jpg",
    description: "This is the description of Reggae.",
    color: "orange-300",
  },
  {
    title: "Rock",
    image: "17.jpg",
    description: "This is the description of Rock.",
    color: "teal-300",
  },
  {
    title: "Soul",
    image: "18.jpg",
    description: "This is the description of Soul.",
    color: "lime-300",
  },
  {
    title: "World",
    image: "19.jpg",
    description: "This is the description of World.",
    color: "red-500",
  },{
    title: "Indie Folk",
    image: "indie-folk.jpg",
    description: "This is the description of Indie Folk.",
    color: "purple-500",
  },
  {
    title: "Soul",
    image: "soul.jpg",
    description: "This is the description of Soul.",
    color: "yellow-500",
  },
  {
    title: "Country",
    image: "country.jpg",
    description: "This is the description of Country.",
    color: "green-500",
  },
  {
    title: "Reggae",
    image: "reggae.jpg",
    description: "This is the description of Reggae.",
    color: "red-300",
  },
  {
    title: "Alternative",
    image: "alternative.jpg",
    description: "This is the description of Alternative.",
    color: "gray-500",
  },
  {
    title: "Funk",
    image: "funk.jpg",
    description: "This is the description of Funk.",
    color: "purple-300",
  },
  {
    title: "Jazz",
    image: "jazz.jpg",
    description: "This is the description of Jazz.",
    color: "blue-300",
  },
  {
    title: "Metal",
    image: "metal.jpg",
    description: "This is the description of Metal.",
    color: "red-100",
  },
  {
    title: "Electronic",
    image: "electronic.jpg",
    description: "This is the description of Electronic.",
    color: "pink-500",
  },
  {
    title: "Hip Hop",
    image: "hip-hop.jpg",
    description: "This is the description of Hip Hop.",
    color: "yellow-300",
  }
];